# Trivial Sparse Random Walks

Working notes for this [SO question](http://stackoverflow.com/questions/31363261/python-library-for-evaluating-random-walks/31477081#31477081)

In [28]:
import scipy.sparse

def random_walk_transition_probability(n, left = 0.3, centre = 0.5, right = 0.2):
    m = 2*n+1
    A  = scipy.sparse.csr_matrix((m, m))
    A += scipy.sparse.diags(centre*np.ones(m), 0)
    A += scipy.sparse.diags(left*np.ones(m-1), -1)
    A += scipy.sparse.diags(right*np.ones(m-1),  1)
    print A.todense()
    x = np.zeros((m,1))
    x[n] = 1.0
    for i in xrange(n):
        x = A.dot(x)
        print x.T
    return x

print random_walk_transition_probability(2)

[[ 0.5  0.2  0.   0.   0. ]
 [ 0.3  0.5  0.2  0.   0. ]
 [ 0.   0.3  0.5  0.2  0. ]
 [ 0.   0.   0.3  0.5  0.2]
 [ 0.   0.   0.   0.3  0.5]]
[[ 0.   0.2  0.5  0.3  0. ]]
[[ 0.04  0.2   0.37  0.3   0.09]]
[[ 0.04]
 [ 0.2 ]
 [ 0.37]
 [ 0.3 ]
 [ 0.09]]


In [31]:
import scipy.sparse as sp
import numpy as np

def random_walk_transition_probability(n, left = 0.3, centre = 0.5, right = 0.2):
    m = 2*n+1
    A  = sp.csr_matrix((m, m))
    A += sp.diags(centre*np.ones(m), 0)
    A += sp.diags(left*np.ones(m-1), -1)
    A += sp.diags(right*np.ones(m-1),  1)
    x = np.zeros((m,1))
    x[n] = 1.0
    for i in xrange(n):
        x = A.dot(x)
    return x



[[ 0.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [32]:
%timeit random_walk_transition_probability(500)

100 loops, best of 3: 7.12 ms per loop


In [33]:
%timeit random_walk_transition_probability(10000)

1 loops, best of 3: 1.06 s per loop


In [ ]:
%timeit random_walk_transition_probability(100000)