In [23]:
from __future__ import print_function

# Python Slice Syntax

This notebook was written in response to a request from a colleague about how slicing works in Python. 

Slicing lets you extract part of a [sequence](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range), of which lists, tuples and ranges are three important examples.  Slicing is one example of a python language construct that makes the language easier to read, write and understand by providing *syntactic sugar* (a simpler to use syntax) that is translated during parsing. 

The table below shows the most common uses of sequence slicing - also presented are the equivalent versions with the syntactic sugar of slicing removed.

| syntax  | description | desugared |
|---------|-------------|-----------|
|`s[:]`     | slice of `s` from `0` to `len(s)` | `s[slice(None,None)]` |
|`s[:i]`    | slice of `s` from `0` to `i` | `s[slice(None, i)]` |
|`s[i:]`    | slice of `s` from `i` to `len(s)` | `s[slice(i, None)]` |
|`s[i:j]`   | slice of `s` from `i` to `j` | `s[slice(i, j)]` |
|`s[i:j:k]` | slice of `s` from `i` to `j` with step `k` | `s[slice(i, j, k)]` |

In cases where index `i` of a sequence `s` is negative, they can be desugared to `len(s)-i`, so `s[-3:]` is equivalent to `s[len(s)-3:]`


In [47]:
lst = range(10)

In [24]:
print(lst[3:8])
print(lst[slice(3, 8)])

[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]


In [52]:
print(lst[3:-2])
print(lst[slice(3, -2)])

[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]


In [25]:
print(lst[4:])
print(lst[slice(4, None)])

[4, 5, 6, 7, 8, 9]
[4, 5, 6, 7, 8, 9]


In [26]:
print(lst[:4])
print(lst[slice(None, 4)])

[0, 1, 2, 3]
[0, 1, 2, 3]


In [28]:
lst = range(20)
print(lst[2:15:2])
print(lst[slice(2,15,2)])

[2, 4, 6, 8, 10, 12, 14]
[2, 4, 6, 8, 10, 12, 14]


# Numpy Indexing

Numpy includes good documentation of [indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), this is mainly here for completeness

In [36]:
import numpy as np

A = np.arange(100).reshape(10,10)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [48]:
# row slice
print(A[1, :])

# column slice
print(A[:, 1])

# block slice
print(A[4:6, 7:9])

[10 11 12 13 14 15 16 17 18 19]
[ 1 11 21 31 41 51 61 71 81 91]
[[47 48]
 [57 58]]


In [53]:
# Advanced indexing 
print(A[:, [3,5,7]])

[[ 3  5  7]
 [13 15 17]
 [23 25 27]
 [33 35 37]
 [43 45 47]
 [53 55 57]
 [63 65 67]
 [73 75 77]
 [83 85 87]
 [93 95 97]]
